storage:
  hnsw_index:
    # Store HNSW index on disk. If set to false, index will be stored in RAM. Default: false
    on_disk: true

service:

  # Host to bind the service on
  host: 127.0.0.1

  # gRPC port to bind the service on.
  grpc_port: 6335

# Set to true to prevent service from sending usage statistics to the developers.
# Read more: https://qdrant.tech/documentation/guides/telemetry
telemetry_disabled: true